# Configuracion General
spring.application.name=E-commerceUribe
spring.jpa.hibernate.ddl-auto=create

# Configuracion de H2 (En memoria)
# URL: jdbc:h2:mem:testdb -> "testdb" es el nombre de la base de datos en memoria.
# Si quieres persistencia, usa: jdbc:h2:file:~/testdb
spring.datasource.url=jdbc:h2:mem:uribedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12

# Habilita la Consola Web de H2
spring.h2.console.enabled=true

# Configuracion de Swagger/OpenAPI (SpringDoc)
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs